services:
  web:
    image: brentpabst/tv-display
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - cors-anywhere

  cors-anywhere:
    image: testcab/cors-anywhere
    ports:
      - 9090:8080
